package models.failure;

public enum DetectionMethods {
	PERIODIC_MAINTENANCE,
	FUNCTIONAL_TESTING,
	INSPECTION,
	PERIODIC_CONDITION_MONITORING,
	CONTINUOUS_CONDITION_MONITORING,
	PRODUCTION_INTERFERENCE,
	CASUAL_OBSERVATION,
	CORRECTIVE_MAINTENANCE,
	ON_DEMAND,
	OTHER
}
